# Generated by Django 3.0rc1 on 2019-11-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='DEFAULT PLAYER NAME')),
                ('cooldown', models.IntegerField(default=20)),
                ('encumbrance', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('gold', models.IntegerField(default=0)),
                ('bodywear', models.TextField(default='NONE')),
                ('footwear', models.TextField(default='NONE')),
                ('inventory', models.CharField(default='[]', max_length=1000)),
                ('status', models.CharField(default='[]', max_length=1000)),
                ('errors', models.CharField(default='[]', max_length=1000)),
                ('messages', models.CharField(default='[]', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=0)),
                ('title', models.TextField(default='DEFAULT TITLE')),
                ('description', models.TextField(default='DEFAULT DESCRIPTION')),
                ('coordinates', models.TextField(default='DEFAULT COORDINATES')),
                ('players', models.CharField(default='[]', max_length=1000)),
                ('items', models.CharField(default='[]', max_length=1000)),
                ('exits', models.CharField(default='[]', max_length=1000)),
                ('cooldown', models.IntegerField(default=20)),
                ('errors', models.CharField(default='[]', max_length=1000)),
                ('messages', models.CharField(default='[]', max_length=1000)),
                ('n_to', models.IntegerField(default=0)),
                ('s_to', models.IntegerField(default=0)),
                ('e_to', models.IntegerField(default=0)),
                ('w_to', models.IntegerField(default=0)),
            ],
        ),
    ]
